# Import Libraries and Fetch Data for EDA:

In [57]:
import numpy as np
import pandas as pd

In [58]:
from data.fetch_data import fetch_ml_data

# EDA on the Fetched Data:

In [59]:
df = fetch_ml_data()
df.head()

,streamer_id,followers,niche,country,avg_viewers,avg_peak_viewers,avg_chat_rate,avg_like_count,total_minutes,total_donations
1,1,99227,Gaming,Canada,2170.60,3260.60,218.00,4629.60,705,1916.70
2,2,77269,Music,Canada,3894.00,5167.00,379.00,5678.50,374,1273.45
3,3,16896,Education,USA,2036.33,3132.67,298.00,4515.00,501,1361.90
4,4,437533,Tech,USA,3313.60,3755.40,211.80,5128.00,631,2135.03
5,5,6421,Tech,USA,2682.60,4019.20,260.40,5557.80,330,1249.65

In [60]:
df.drop('streamer_id',axis=1,inplace=True)

In [61]:
df.isnull().sum()

followers           0
niche               0
country             0
avg_viewers         0
avg_peak_viewers    0
avg_chat_rate       0
avg_like_count      0
total_minutes       0
total_donations     0
dtype: int64

Here we don't have any missing values for now so it's ok.

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 1 to 19
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   followers         19 non-null     int64
 1   niche             19 non-null     object
 2   country           19 non-null     object
 3   avg_viewers       19 non-null     object
 4   avg_peak_viewers  19 non-null     object
 5   avg_chat_rate     19 non-null     object
 6   avg_like_count    19 non-null     object
 7   total_minutes     19 non-null     int64
 8   total_donations   19 non-null     object
dtypes: int64(2), object(7)
memory usage: 1.5+ KB

Some Columns are objects while others are int we need to convert these objects columns into the int one.

## Converting Categorical Columns into numerical:

In [63]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

In [64]:
cat_cols = ['niche', 'country']
encoded_data = encoder.fit_transform(df[cat_cols])

In [65]:
encoded_df = pd.DataFrame(
    encoded_data, 
    columns=encoder.get_feature_names_out(cat_cols),
    index=df.index
)

In [66]:
encoded_df

,niche_Education,niche_Finance,niche_Gaming,niche_IRL,niche_Music,niche_Sports,niche_Tech,country_Canada,country_Germany,country_India,country_Japan,country_USA
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
5,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
6,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
9,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
12,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
13,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
14,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
15,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
18,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [67]:
df = pd.concat([df.drop(columns=cat_cols), encoded_df], axis=1)

In [68]:
df

,followers,avg_viewers,avg_peak_viewers,avg_chat_rate,avg_like_count,total_minutes,total_donations,niche_Education,niche_Finance,niche_Gaming,niche_IRL,niche_Music,niche_Sports,niche_Tech,country_Canada,country_Germany,country_India,country_Japan,country_USA
1,99227,2170.60,3260.60,218.00,4629.60,705,1916.70,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,77269,3894.00,5167.00,379.00,5678.50,374,1273.45,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,16896,2036.33,3132.67,298.00,4515.00,501,1361.90,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,437533,3313.60,3755.40,211.80,5128.00,631,2135.03,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
5,6421,2682.60,4019.20,260.40,5557.80,330,1249.65,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
6,155588,2739.60,3686.60,304.80,6540.20,750,1289.99,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7,399209,1113.50,2298.25,333.00,6408.75,465,2504.03,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8,70990,2456.57,3469.29,366.43,4392.00,1074,2233.94,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
9,61477,1398.33,3139.67,297.50,5312.50,555,1700.18,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10,364051,1982.63,2852.75,340.63,4501.38,1521,1784.38,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
11,213224,1620.25,2908.38,263.75,5113.50,1188,1082.67,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
12,188592,1598.00,2718.13,207.50,4804.38,1231,1148.42,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
13,414769,2349.75,3044.50,267.25,4110.25,960,1002.67,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
14,366933,2779.67,2883.00,182.67,4100.33,370,844.36,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
15,173881,3799.40,4453.00,289.40,3863.60,720,1840.21,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16,173978,2877.25,4325.25,277.00,8507.00,466,1158.17,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
17,438025,3314.17,4632.00,258.67,4503.50,1066,758.85,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
18,126578,2970.00,4355.50,485.00,6965.00,181,1065.16,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19,78464,2753.86,3656.86,329.86,4627.43,923,1527.39,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [69]:
df.isnull().sum()
# If we still doesnt get any missing values we're good to go.

followers           0
avg_viewers         0
avg_peak_viewers    0
avg_chat_rate       0
avg_like_count      0
total_minutes       0
total_donations     0
niche_Education     0
niche_Finance       0
niche_Gaming        0
niche_IRL           0
niche_Music         0
niche_Sports        0
niche_Tech          0
country_Canada      0
country_Germany     0
country_India       0
country_Japan       0
country_USA         0
dtype: int64

In [70]:
cols_to_numeric = [
    'avg_viewers', 'avg_peak_viewers', 'avg_chat_rate', 
    'avg_like_count', 'total_donations'
]
for col in cols_to_numeric:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 1 to 19
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   followers         19 non-null     int64
 1   avg_viewers       19 non-null     float64
 2   avg_peak_viewers  19 non-null     float64
 3   avg_chat_rate     19 non-null     float64
 4   avg_like_count    19 non-null     float64
 5   total_minutes     19 non-null     int64
 6   total_donations   19 non-null     float64
 7   niche_Education   19 non-null     float64
 8   niche_Finance     19 non-null     float64
 9   niche_Gaming      19 non-null     float64
 10  niche_IRL         19 non-null     float64
 11  niche_Music       19 non-null     float64
 12  niche_Sports      19 non-null     float64
 13  niche_Tech        19 non-null     float64
 14  country_Canada    19 non-null     float64
 15  country_Germany   19 non-null     float64
 16  country_India     19 non-null     float64
 17  country_Japan     19 non-null     float64
 18  country_USA       19 non-null     float64
dtypes: float64(17), int64(2)
memory usage: 2.9 KB

## Correlation with our label:

In [72]:
corr_mat = df.corr()
donation_corr = corr_mat['total_donations'].sort_values(ascending=False)

In [73]:
donation_corr

total_donations     1.000000
niche_IRL           0.562323
country_Canada      0.308492
niche_Finance       0.217235
country_USA         0.176038
niche_Tech          0.161412
avg_chat_rate       0.136766
country_Germany     0.072738
total_minutes       0.047487
niche_Gaming       -0.009025
followers          -0.014636
niche_Education    -0.051892
avg_like_count     -0.060002
avg_viewers        -0.241379
avg_peak_viewers   -0.280603
country_India      -0.280830
country_Japan      -0.383232
niche_Music        -0.389941
niche_Sports       -0.403167
Name: total_donations, dtype: float64

# Correlation Matrix Observations:

## 1. Positive Correlations:
These features move in the same direction as your donations. When these numbers go up, the money usually goes up too. These are your strongest predictors.

### niche_IRL (+0.56): 
Niche has a very strong positive connection, suggesting that IRL content is currently the most profitable niche in your dataset.

### country_Canada (+0.31): 
Streams from Canada are strongly associated with higher donation totals.

### niche_Finance (+0.22): 
Finance-related content attracts viewers who are more likely to contribute financially.

### country_USA (+0.18): 
It is slightly less influential than Canada in this specific data batch.

### niche_Tech (+0.16): 
Tech content shows a healthy positive relationship with revenue.

### avg_chat_rate: 0.14
Streamer's engagement with it's chat drives his revenue.

## 2. Negative Correlation
These features move in the opposite direction. Surprisingly, in your data, higher numbers in these columns often mean lower total donations.

### niche_Sports (-0.40) & niche_Music (-0.39): 
For some reason, these niches are currently seeing the lowest donation totals per stream.

### country_Japan (-0.38) & country_India (-0.28): 
These geographic regions currently show an inverse relationship with the total donation amounts recorded.

### avg_peak_viewers (-0.28) & avg_viewers (-0.24): 
It suggests that as streams get massive, the donation total actually drops. Smaller, tighter communities are out-earning the huge crowds.

## 3. Uncorrelated
These features have scores very close to 0. They are neutral and don't seem to have any meaningful mathematical impact on donations right now.

### total_minutes (+0.04): 
Whether a stream is long or short doesn't seem to change how much money it makes.

### niche_Gaming (-0.01): 
Surprisingly, being a Gamer doesn't positively or negatively impact donations here; it's almost perfectly neutral.

### followers (-0.01): 
Having millions of followers doesn't guarantee more donations than a small streamer.

### avg_like_count (-0.06): 
Likes do look good but don't reliably predict how much money will be donated.

# Columns to Drop:

In [75]:
# The columns we decided to remove based on low/neutral correlation
COLS_TO_DROP = [
    'followers', 
    'total_minutes', 
    'avg_like_count', 
    'niche_Gaming', 
    'streamer_id',      # Metadata, not a feature
    'total_donations'   # This is our Target (y), so it can't be in X
]